################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
OSAL_SampleLight.obj: ../OSAL_SampleLight.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="OSAL_SampleLight.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

OnBoard.obj: ../OnBoard.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="OnBoard.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ZMain.obj: ../ZMain.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="ZMain.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cx2538_setup.obj: ../cx2538_setup.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="cx2538_setup.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cx2538_startup_ccs.obj: ../cx2538_startup_ccs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="cx2538_startup_ccs.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

zcl_ha.obj: ../zcl_ha.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="zcl_ha.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

zcl_sampleapps_ui.obj: ../zcl_sampleapps_ui.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="zcl_sampleapps_ui.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

zcl_samplelight.obj: ../zcl_samplelight.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="zcl_samplelight.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

zcl_samplelight_data.obj: ../zcl_samplelight_data.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/bin/armcl" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\Coordinator.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wConfig.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wCoord.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wRouter.cfg" --cmd_file="C:\Development\Ti\zstack3.1\ZCoord\Config\f8wZCL.cfg"  -mv7M3 --code_state=16 -me --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/hal/target/CC2538" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/inc" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/driverlib/cc2538/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/bsp/srf06eb_cc2538/drivers/source" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/high_level" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05/single_chip" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mac/low_level/srf05" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/mt" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/osal/include" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/sdata" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/services/saddr" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/af" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/bdb" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/GP" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/nwk" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sapi" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sec" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/sys" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zcl" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/stack/zdo" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac" --include_path="C:/Development/Ti/zstack3.1/ZStackLib/zmac/f8w" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.2.LTS/include" --define=ccs --define=DEBUG --define=CC2538_USE_ALTERNATE_INTERRUPT_MAP -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --wchar_t=16 --abi=eabi --preproc_with_compile --preproc_dependency="zcl_samplelight_data.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


